#!/usr/bin/env python

def get_options():
    import argparse

    description = 'Draw a scree-plot from MDS eigenvalues'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('eigenvalues',
                        help='Eigenvalues file '
                             '(output of pyseer with the --scree-plot option)')
    
    parser.add_argument('--max-dimensions',
                        type=int,
                        default=20,
                        help='Maximum dimensions to plot [Default: 20]')
    parser.add_argument('--output',
                        default='scree_plot.png',
                        help='Plot filename [Default: scree_plot.png]')

    return parser.parse_args()

if __name__ == "__main__":
    options = get_options()

    import sys
    import pandas as pd
    import matplotlib.pyplot as plt

    m = pd.read_table(options.eigenvalues)
    if m.shape[0] > options.max_dimensions:
        sys.stderr.write('Plotting only the first %d PCs out of %d\n' % (options.max_dimensions,
                                                                         m.shape[0]))
        m = m.iloc[:options.max_dimensions]

    plt.figure(figsize=(0.25*m.shape[0], 3))

    plt.plot(range(m.shape[0]),
             m['eigenvalue'],
             'ko-')
    plt.ylabel('eigenvalue')
    plt.xlabel('PCs')
    plt.xticks(range(m.shape[0]),
               range(1, m.shape[0]+1),
               rotation=90)

    plt.xlim(-0.25, m.shape[0]-0.75)
    plt.tight_layout()

    plt.savefig('scree_plot.png', dpi=150)
